spring.application.name=location-service
server.port=8082


spring.data.redis.host=localhost
spring.data.redis.port=6380

management.endpoints.web.exposure.include=health,info

spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:keys/public.pem